openapi: 3.0.1
info:
  title: QuerySuccessfulResults
  description: API Definition of QuerySuccessfulResults
  version: 1.0.0
servers:
- url: http://localhost:8290/salesforce
paths:
  /createquery:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /getqueryJobinfo:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /getQueryJobResults:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
